import React from "react";
import Head from "next/head";
import Link from "next/link";

//This is a function that displays my web apps
export default function Pantry() {
  return (
    <div className="center">
      <Head>
        <title>Pantry</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <Link href="/">
      <button className="home">Home</button>
      </Link>
      <div className="project-page">
        <h1 className="delaine">Pantry</h1>
          <p>
            This is app that allows you to create a shopping list aswell
            as take inventory of your current food supply. This app also lets
            you know which foods are expired and which foods are near
            expiration. It is seperated into 2 tabs: shopping list and pantry.
            For both the shopping list and pantry sections, you can add food
            into your list by filling out a form. Please click on the button
            below to view and use the app.
            <p>
              <h3>Technologies used:</h3>
              <ul>
                <li id="project">MongoDB</li>
                <li id="project">Express</li>
                <li id="project">ReactJS</li>
                <li id="project">NodeJS</li>
                <li id="project">NextJS</li>
              </ul>{" "}
            </p>
          </p>
          <div>
            <button>
              <a href="https://pantry-dusky.vercel.app/">Go to web app</a>
            </button>
            <button>
              {" "}
              <a href="https://github.com/delaine3/Pantry"> Source Code</a>
            </button>
          </div>
      </div>
    </div>
  );
}
