import React from "react";
import Head from "next/head";
import Link from "next/link";

//This is a function that displays my web apps
export default function SnakeGame() {
  return (
    <div className="center">
      <Head>
        <title>Snake game </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <Link href="/">
      <button className="home">Home</button>
      </Link>
      <div className="project-page">
      <h1 className="delaine">Snake game </h1>

          <p>
            This a snake game. The goal is to direct a snake using the up, down, left and right arrows to food withouth hitting the boundaries of the box. After the game is over the player is presented with a
            form that allows them to save their score. There is also a page that contains a leaderboard, containing the scores of other players in descending order.
            <p>
              {" "}
              Some of the code and ideas from my game are adapted from the
              following
              <a href="https://www.youtube.com/watch?v=lhNdUVh3qCc&t=3s">
                FreeCodeCamp Tutorial Video.
              </a>{" "}
              You can find the original source code of this tutorial in the
              following
              <a href="https://github.com/kubowania/Nokia3310-Snake">
                Github repo
              </a>{" "}
              The original source contains an MIT license which allows anyone
              to use it. The game in the{" "}
              <a href="https://www.youtube.com/watch?v=lhNdUVh3qCc&t=3s">
                FreeCodeCamp Tutorial Video
              </a>{" "}
              is made using vanilla javascript and minimal css. Mine is
              created using the technologies below.
            </p>
            <p>
              <h3>Technologies used:</h3>
              <ul>
                <li id="project">MongoDB</li>
                <li id="project">Express</li>
                <li id="project">ReactJS</li>
                <li id="project">NodeJS</li>
                <li id="project">NextJS</li>
              </ul>{" "}
            </p>
          </p>
          <button>
            <a href="https://snake-game-five-dun.vercel.app/">
            Go to Delaine&rsquo;s version of the game
            </a>
          </button>
          <button>
            <a href="https://github.com/delaine3/snake_game">
            Go to Delaine&rsquo;s source code
            </a>
          </button>
      </div>
    </div>
  );
}
