import React from "react";
import Head from "next/head";
import Link from "next/link";

//This is a function that displays my web apps
export default function Index() {
  return (
    <div>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <div>
        <h1 className="delaine">Delaine Abner : Portfolio</h1>
        <h1>Hi, my name is Delaine. Welcome To my portfolio.</h1>
        <ul className="tile-list">
          <li className="project-list">
            <h1>Certificates</h1>
            <p>These are the certificates I have attained thus far.</p>
          
            <ul>
              <Link href="/certificates">
                <button>Certificates</button>
              </Link>
            </ul>
          </li>
          <li className="project-list">
            <h1>Web Apps</h1>
            <p>These are projects that I have worked on. They are built using a combination of the following technologies. </p>
            <ul>
              <li id="project">MongoDB</li>
              <li id="project">Express</li>
              <li id="project">ReactJS</li>
              <li id="project">NextJS</li>
              <li id="project">NodeJS</li>
              
            </ul>{" "}
            <ul>
              <Link href="/webProjects">
                <button>Go To Web Apps</button>
              </Link>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  );
}
